steps:
  - name: Hello world action
    with: # Set the secret as an input
      super_secret: ${{ secrets.TEST_SECRET }}
    env: # Or as an environment variable
      super_secret: ${{ secrets.TEST_SECRET }}
    run: |
      echo $super_secret
