name: Secret Test

on:
  push:
    branches: [ "master", "main" ]
jobs:
  secret_test:
    name: Secret Test
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        env: # Or as an environment variable
          super_secret: ${{ secrets.TEST_SECRET }}
        run: |
          echo $super_secret
